trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformWorkingDirectory: 'Terraform'

steps:
# Установка Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

# Установка зависимостей Python
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python dependencies'

# Установка Terraform вручную
- script: |
    curl -o terraform.zip https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_linux_amd64.zip
    unzip terraform.zip
    sudo mv terraform /usr/local/bin/
    terraform -version
  displayName: 'Install Terraform'

# Инициализация Terraform
- script: |
    terraform -chdir=$(terraformWorkingDirectory) init
  displayName: 'Terraform Init'

# Планирование Terraform
- script: |
    terraform -chdir=$(terraformWorkingDirectory) plan
  displayName: 'Terraform Plan'

# Применение Terraform
- script: |
    terraform -chdir=$(terraformWorkingDirectory) apply -auto-approve
  displayName: 'Terraform Apply'